notifications:
  email: false

language: node_js
node_js:
  - node

services:
  - docker

before_install:
  - docker pull trzeci/emscripten:1.39.8-upstream

install:
  - npm install
  - make

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  - provider: npm
    email: $NPM_EMAIL
    api_key: $NPM_KEY
    on:
      tags: true
    skip_cleanup: true
